### ISSUE TITLE
固件中AdGuard Home登录账号和密码

### ISSUE THREAD

**Issue by caesaranthony** [DHDAXCW/NanoPi-R2S-rk3328#1]
DHDAXCW @ FusionWrt R22.3.13 (2022-05-26) / LuCI Master (git-22.146.34683-df8288f)
此版本固件中AdGuard Home插件已经启用，并设置了登陆密码
请问密码，谢谢

**Comment by kinist** [comment]
我也知道密码是啥

**Comment by kinist** [comment]
我也想知道密码是啥

**Comment by caesaranthony** [comment]
可以自行重置密码

**Comment by ERRORCODE6** [comment]
直接删除配置文件重置，，，
