### ISSUE TITLE
r2s 7.4固件频率只有600   阿里云盘能用   7.4以前固件阿里云盘启动不了

### ISSUE THREAD

**Issue by xixiaichirou** [DHDAXCW/NanoPi-R2S-rk3328#10]

**Comment by xixiaichirou** [comment]
r2s

**Comment by xixiaichirou** [comment]
> 我竟然没注意。。。等今天版本，今天在搞了

刷了最新版问题还是一个样.试了试CPU性能模式头两个没变化
![1657267569(1)](https://user-images.githubusercontent.com/108857344/177948023-3e62cbac-b889-4915-a495-43eac12774e7.png)
![1657267589(1)](https://user-images.githubusercontent.com/108857344/177948070-b16656fc-bf5f-4ecd-b8d8-e46409f13c68.png)

**Comment by xixiaichirou** [comment]
有没有可能是显示错误  实际上是没问题的....

**Comment by toniexly** [comment]
我这里没有个问题呃，频率默认就会自动调整。（我没有动那个CPU调节插件）
