### ISSUE TITLE
20220812正式版和稳定版中都没有smartdns插件，大家有没有这问题？

### ISSUE THREAD

**Issue by nietsme** [DHDAXCW/NanoPi-R2S-rk3328#17]
RT！！！
下面是稳定版日志：
[稳定版-内核日志.txt](https://github.com/DHDAXCW/NanoPi-R2S-rk3328/files/9355951/-.txt)
[稳定版-系统日志.txt](https://github.com/DHDAXCW/NanoPi-R2S-rk3328/files/9355953/-.txt)

下面是稳定版插件截图
![稳定版-插件截图](https://user-images.githubusercontent.com/437426/185025140-fb33786d-95c5-47ea-a87e-35283c1312f3.png)

下面是稳定版list-installed |grep dns列出的内容。只有smartdns没有luci-app界面
![稳定版listinstalledgrepdns](https://user-images.githubusercontent.com/437426/185025467-e2104a1c-9fcd-49bb-87bb-39f9f7bf686e.png)

**Comment by kljkyzsl** [comment]
+1 确实没找到smartdns

**Comment by DHDAXCW** [comment]
移除了

**Comment by nietsme** [comment]
> 

ok，截图上还有。我以为有。
https://github.com/DHDAXCW/NanoPi-R2S-rk3328
