### ISSUE TITLE
你的全部插件的示例图片里我看都有SmartDNS,结果下载的固件里面却没有

### ISSUE THREAD

**Issue by mikmeng007** [DHDAXCW/NanoPi-R2S-rk3328#21]
你的全部插件的示例图片里我看都有SmartDNS,结果下载的固件里面却没有，这是怎么回事啊？ 要上外网，内外网不同的nameserver，这个肯定是很影响访问网站速度的，SmartDNS这么重要的插件都被你拿掉了，不知道是为什么？

**Comment by ecator** [comment]
x86的固件好像有，不过R2S这个确实没有了，没有办法只能直接用passwall2的DNS，也可以分直连的DNS和远程代理的DNS两个，目前来看用着还行，默认的dnsmasq也不受影响（好像是自动把passwall2的DNS设置成了dnsmasq的上游服务器）

**Comment by TRainbow713** [comment]
其实是有，安装compat的luci之后重启就有了。
