### ISSUE TITLE
NaiveProxy 配置后无法科学上网

### ISSUE THREAD

**Issue by Acydmr** [DHDAXCW/NanoPi-R2S-rk3328#27]
最新版本以及往前三个版本都测试过， 均无法使用 NaiveProxy，百度 连通性测试ok， Google 连通性测试失败

**Comment by DHDAXCW** [comment]
等会我看看

**Comment by DHDAXCW** [comment]
用什么插件？我算命不出来

**Comment by Acydmr** [comment]
SS PLUS 里面的 NaiveProxy 协议

**Comment by Acydmr** [comment]
SS PLUS 里面的 NaiveProxy 协议
