### ISSUE TITLE
slim版会有无法保存设置的问题

### ISSUE THREAD

**Issue by chonghai** [DHDAXCW/NanoPi-R2S-rk3328#37]
试了很多个slim版，安装一段时间后，修改里面的配置都会出现无法保存配置的问题。
现在换用full版，暂时还没有出现过这个问题。
猜测可能是缺少什么文件，导致系统错乱，无法正常保存配置。

**Comment by DHDAXCW** [comment]
不要用ext4就行了

**Comment by chonghai** [comment]
> 不要用ext4就行了

哦，ext4比较容易出问题吗？（谢谢回复！）

**Comment by xiananliu** [comment]
我用squashfs 也有保存不了的问题

**Comment by qzy980427** [comment]
> 不要用ext4就行了

大佬，我用squashfs也保存不了。最新版本也是这样

**Comment by YangZeyu95** [comment]
重新挂载一下硬盘，mount -o remount rw /
