### ISSUE TITLE
在精简版的基础上希望增加wireguard插件，通过软件包安装时发现缺少kmod-wireguard，

### ISSUE THREAD

**Issue by felixxiao99** [DHDAXCW/NanoPi-R2S-rk3328#38]
大大好，我想让软路由的功能尽量单纯一些，只具备科学上网和wireguard的功能，于是在精简版的基础上希望增加wireguard插件，通过软件包界面安装时发现缺少kmod-wireguard这个依赖包，有劳大大加入这个包，感谢

**Comment by DHDAXCW** [comment]
明天安排

**Comment by felixxiao99** [comment]
@DHDAXCW 谢谢大大
