### ISSUE TITLE
r2s的温控脚本没有执行

### ISSUE THREAD

**Issue by xiananliu** [DHDAXCW/NanoPi-R2S-rk3328#39]
/etc/init.d/fa-rk3328-pwmfan 该启动项没有执行权限，导致该脚本启动时没有被执行。

**Comment by xiananliu** [comment]
04.28版本问题依旧

**Comment by DHDAXCW** [comment]
下个版本会给脚本授权

**Comment by xiananliu** [comment]
这个也需要授权哦  chmod u+x /usr/bin/start-rk3328-pwm-fan.sh
