### ISSUE TITLE
如何在线升级？

### ISSUE THREAD

**Issue by JoeyVan** [DHDAXCW/NanoPi-R2S-rk3328#4]
Readme 中有提到在 TTYD 中输入指令在线升级。但是没有给指令。
个人认为通过 TTYD 在线升级的功能很有用！
另外，这个在线升级会不会抹掉之前的设置内容？

**Comment by woaidianqian** [comment]
同问

**Comment by mayjack0312** [comment]
同问+1，每次升级都重刷重配置确实有点麻烦

**Comment by yocus** [comment]
![image](https://user-images.githubusercontent.com/22991092/193988830-dbdae641-79d3-4762-9d1f-669a7bbfd3e0.png)
确实没有给指令~~
