### ISSUE TITLE
4.28 号的 带docker的版本 会不定时重启

### ISSUE THREAD

**Issue by shiyuanGame** [DHDAXCW/NanoPi-R2S-rk3328#50]
4.28 号的 带docker的版本 会不定时重启
导致公网ip一直变

**Comment by DHDAXCW** [comment]
收到，等下版本我测试再发布

**Comment by DHDAXCW** [comment]
你运行是什么东西，我今晚看看

**Comment by shiyuanGame** [comment]
> 你运行是什么东西，我今晚看看

我运行的青龙面板，但是我发现我关掉docker一样会重启，我看tg群里又群友跟我一样

**Comment by shiyuanGame** [comment]
大佬的邮箱是多少 我可以把我系统日志和内核日志发您看一下，我看tg私聊您被拒收了

**Comment by DHDAXCW** [comment]
直接发这里

**Comment by shiyuanGame** [comment]
> [xiaoqi636322@gmail.com](mailto:xiaoqi636322@gmail.com) 用txt

刚看到，已经发送了  刚刷机的前几天一直重启，但是现在我发现 稳定运行了2天没有重启了

**Comment by DHDAXCW** [comment]
测试下最新的

**Comment by shiyuanGame** [comment]
> 测试下最新的

好的谢谢大佬！！  我明天测试一下，今天要加班回家太晚了没时间折腾。

**Comment by shiyuanGame** [comment]
> 测试下最新的

测试完毕 还是不定时重启

**Comment by shiyuanGame** [comment]
> 测试下最新的

这次重启以后docker也重置了  镜像和容器都不见了

**Comment by shiyuanGame** [comment]
我安装去年带docker版本的r2s 固件 目前还没有自动重启  但是发现 安装server酱安装不显示，重启以后发现固件不会启动了，必须拔掉网线 再次重启才能正常启动。正常启动再插上网线 才能正常使用， 重启以后  server酱还是找不到，但是在软件源里显示已经安装。 手动重启的情况下docker的也会被重置，发现镜像和容器也不见了，
