### ISSUE TITLE
4.27 docker版遇到不定时重启问题

### ISSUE THREAD

**Issue by DHDAXCW** [DHDAXCW/NanoPi-R2S-rk3328#51]
遇到重启请在这里提供一下使用说明，我今晚开始准备检查修复
把你们在docker上开的是什么东西发到这里

**Comment by shiyuanGame** [comment]
刚玩docker 有些不是很懂  
镜像： whyour/qinglong:latest

容器
qinglong
ID: c141b42a3cde
Image: whyour/qinglong:latest
Size: 61 MB/338 MB

还需要我配合哪些操作 请大佬回复
