### ISSUE TITLE
r2s docker 版本还是会重启 一天重启几次

### ISSUE THREAD

**Issue by shiyuanGame** [DHDAXCW/NanoPi-R2S-rk3328#58]
r2s docker 版本还是会重启 一天重启几次

**Comment by shiyuanGame** [comment]
[日志zip](https://github.com/DHDAXCW/NanoPi-R2S-rk3328/files/12210299/default.zip)

**Comment by gaoweihe** [comment]
I suppose it's heating problem. Locking freq to 408M worked for me.

**Comment by shiyuanGame** [comment]
不用了 r2s  已经出手了  换x86了 问题我给关一下
